### ISSUE TITLE
ttf

### ISSUE THREAD

**Issue by sysmat** [timrs2998/pdf-builder#15]
Is it possible to use  ttf file for fonts?

Regards, Tomaž

**Comment by timrs2998** [comment]
Yes. First, load the ttf file as a PDFont. You can then assign the PDFont to a TextElement.

```groovy
PDFont font = PDTrueTypeFont.loadTTF(document, "Arial.ttf");
TextElement textElement = new TextElement(document);
textElement.setPdFont(font);
```

Make sure the font is embedded inside the document when you distribute to end-users.

See:
 * https://pdfbox.apache.org/1.8/cookbook/workingwithfonts.html
 * https://timrs2998.github.io/pdf-builder/com/github/timrs2998/pdfbuilder/Element.html#setPdFont-p-
 * https://memorynotfound.com/apache-pdfbox-add-embedded-font-pdf-document/

**Comment by sysmat** [comment]
Thx for information I was thinking as DSL
