### ISSUE TITLE
Into the Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter

### ISSUE THREAD

**Issue by vlipovetskii** [timrs2998/pdf-builder#24]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

_May 1st, 2021 | Bintray services will no longer be available. GoCenter, and ChartCenter services will no longer be available to non-Artifactory clients. (ConanCenter is not affected)._

```
repositories {
  maven("https://dl.bintray.com/timrs2998/maven")
}
```

**Comment by jasin** [comment]
so what can we use as an alternate?

**Comment by timrs2998** [comment]
I migrated the build from Bintray and TravisCI to GitHub package registry and GitHub actions

https://github.com/timrs2998?tab=packages&repo_name=pdf-builder
