### ISSUE TITLE
TableElement cannot have elements below it

### ISSUE THREAD

**Issue by timrs2998** [timrs2998/pdf-builder#9]
Need to rewrite the height calculation for TableElement to support elements appearing after a table

**Comment by geertijewski** [comment]
It looks like in `Document.kt` `renderInstance` inside the `children.fold()` the `adjustedStartY` is added again, however in TableElement.kt the height starts with `startY`. So for all table elements the start Y position is added twice, pushing all elements below further down.

Compare e.g. to TextElement `instanceHeight` which does not add `startY`.
